//
//  PopularFilmsPresenter.swift
//  Movies
//
//  Created by Alex Cuello ortiz on 06/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol PopularFilmsPresenterInput {
    
}

protocol PopularFilmsPresenterOutput: class {
    
}

class PopularFilmsPresenter: PopularFilmsPresenterInput {
    
    weak var output: PopularFilmsPresenterOutput?
    
    // MARK: Presentation logic
    
}
