//
//  PopularFilmsPresenter.swift
//  Movies
//
//  Created by Alex Cuello ortiz on 06/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol PopularFilmsPresenterInput {
    func presentFilms(response: PopularFilmsScene.PopularFilmsList.Response)
}

protocol PopularFilmsPresenterOutput: class {
    func displayFilms(viewModel: PopularFilmsScene.PopularFilmsList.ViewModel)
}

class PopularFilmsPresenter: PopularFilmsPresenterInput {
    
    weak var output: PopularFilmsPresenterOutput?
    
    func presentFilms(response: PopularFilmsScene.PopularFilmsList.Response) {
        let films = response.films
        var displayFilms:[PopularFilmsScene.PopularFilmsList.DisplayedFilm] = []
        
        var tmdbError:PopularFilmsScene.PopularFilmsList.TmdbError!
        
        if let error = response.error {
            switch error {
            case .cannotGet(_):
                tmdbError = PopularFilmsScene.PopularFilmsList.TmdbError(title: "Error", description: "Something went wrong, try later or restart the app.")
            }
            
        }
        else {
            for film in films {
                let displayFilm = PopularFilmsScene.PopularFilmsList.DisplayedFilm(title: film.title, year: film.year, overview: film.overview, pictureURL: film.pictureURL)
                displayFilms.append(displayFilm)
            }
        }
        
        let viewModel = PopularFilmsScene.PopularFilmsList.ViewModel(displayFilms: displayFilms, tmdbError: tmdbError)
        output?.displayFilms(viewModel: viewModel)
        
    }
}
