//
//  PopularFilmsInteractor.swift
//  Movies
//
//  Created by Alex Cuello ortiz on 06/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol PopularFilmsInteractorInput {
    func getFilms(request: PopularFilmsScene.PopularFilmsList.Request)
}

protocol PopularFilmsInteractorOutput {
    func presentFilms(response: PopularFilmsScene.PopularFilmsList.Response)
}

protocol PopularFilmsDataSource {
    
}

protocol PopularFilmsDataDestination {
    
}

class PopularFilmsInteractor: PopularFilmsInteractorInput, PopularFilmsDataSource, PopularFilmsDataDestination {
    
    var output: PopularFilmsInteractorOutput?
    var tmdbAPIStore = TmdbAPIStore()
    
    // MARK: Business logic
    func getFilms(request: PopularFilmsScene.PopularFilmsList.Request) {
        tmdbAPIStore.getPopularFilmsDesc(page: request.page) { (result) in
            switch result {
            case .success(result: let films):
                let response = PopularFilmsScene.PopularFilmsList.Response(films: films, error: nil)
                self.output?.presentFilms(response: response)
            case .failure(error: let error):
                let response = PopularFilmsScene.PopularFilmsList.Response(films: [], error: error)
                self.output?.presentFilms(response: response)
            }
        }
    }

}
