//
//  PopularFilmsInteractor.swift
//  Movies
//
//  Created by Alex Cuello ortiz on 06/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol PopularFilmsInteractorInput {
    
}

protocol PopularFilmsInteractorOutput {
    
}

protocol PopularFilmsDataSource {
    
}

protocol PopularFilmsDataDestination {
    
}

class PopularFilmsInteractor: PopularFilmsInteractorInput, PopularFilmsDataSource, PopularFilmsDataDestination {
    
    var output: PopularFilmsInteractorOutput?
    
    // MARK: Business logic
    

}
