//
//  PopularFilmsViewController.swift
//  Movies
//
//  Created by Alex Cuello ortiz on 06/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol PopularFilmsViewControllerInput {
    
}

protocol PopularFilmsViewControllerOutput {
    
}

class PopularFilmsViewController: UIViewController, PopularFilmsViewControllerInput {
    
    var output: PopularFilmsViewControllerOutput?
    var router: PopularFilmsRouter?
    
    // MARK: Object lifecycle
    @IBOutlet weak var popularFilmsTableView: UITableView!
    
    struct cellIdentifiers {
        static let popularFilmCell = "popularFilmCell"
    }
    
    static let film1 = PopularFilmsScene.PopularFilmsList.DisplayedFilm.init(title: "Star Wars: The Last Jedi", year: "2017", overview: "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.", pictureURL: "http://image.tmdb.org/t/p/w185/xGWVjewoXnJhvxKW619cMzppJDQ.jpg")
    static let film2 = PopularFilmsScene.PopularFilmsList.DisplayedFilm.init(title: "Blade Runner 2049", year: "2017", overview: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.", pictureURL: "http://image.tmdb.org/t/p/w185/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg")
    static let film3 = PopularFilmsScene.PopularFilmsList.DisplayedFilm.init(title: "Blade", year: "2017", overview: "Thirty years after the events of the first film.", pictureURL: "http://image.tmdb.org/t/p/w185/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg")
    var displayedPopularFilms: [PopularFilmsScene.PopularFilmsList.DisplayedFilm] = [film1, film2, film3]
    
    
    override func awakeFromNib() {
        super.awakeFromNib()
        PopularFilmsConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureTableViewOnLoad()
        
        
    }
    
    // MARK: Requests
    
    
    // MARK: Display logic
    
    // MARK: UI Events
    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension PopularFilmsViewController: PopularFilmsPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
