//
//  PopularFilmsConfigurator.swift
//  Movies
//
//  Created by Alex Cuello ortiz on 06/01/2018.
//  Copyright (c) 2018 Alex Cuello ortiz. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension PopularFilmsInteractor: PopularFilmsViewControllerOutput, PopularFilmsRouterDataSource, PopularFilmsRouterDataDestination {
}

extension PopularFilmsPresenter: PopularFilmsInteractorOutput {
}

class PopularFilmsConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = PopularFilmsConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: PopularFilmsViewController) {
        
        let presenter = PopularFilmsPresenter()
        presenter.output = viewController
        
        let interactor = PopularFilmsInteractor()
        interactor.output = presenter
        
        let router = PopularFilmsRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
